### ISSUE TITLE
生成的成员变量为什么开头没有加m，且不是private的？

### ISSUE THREAD

**Issue by tedzyc** [dongjunkun/butterknife-plugin#2]
1）R.id.btn_foo生成的成员变量为btnFoo, 而不是mBtnFoo. 但是我看你readme里面的效果图就是mText这种带m的。

2）生成的变量没有private修饰符，这和我所有成员变量都加protect/private的风格不搭
3）另外问一下，您的plugin是butterknife-zelezny的简化版吗。你的效果图和butterknife-zelezny给的效果图：显示的内容不一样

**Comment by dongjunkun** [comment]
在设置里面看一下，有可能没有加前缀，加一下便是

**Comment by tedzyc** [comment]
不会加
是https://github.com/dongjunkun/butterknife-plugin/blob/master/src/com/avast/android/butterknifezelezny/Settings.java，还是Settings.form文件里面，是不是和里面的那个...prefix有关

**Comment by dongjunkun** [comment]
android studio的设置

**Comment by tedzyc** [comment]
找到了，有效果
![setm](https://cloud.githubusercontent.com/assets/6257771/12500299/bd495d8e-c0ec-11e5-8485-ff04bf2d7e2a.png)
